import * as path from 'path';
import * as fs from 'fs';
import * as vscode from 'vscode';
import { XMLParser } from 'fast-xml-parser';
import { CoverageMap, PerTestCoverage, FileCoverage, LineCoverage } from './types';
import { log, logVerbose, logError } from './logger';

const MAX_XML_SIZE = 50 * 1024 * 1024; // 50 MB

/**
 * Manages the coverage map: a bidirectional mapping between source lines and tests.
 *
 * Forward map (perTestCoverage):  testId → Set<"filePath:line">
 * Reverse map (coverageMap):      filePath → lineNumber → Set<testId>
 */
export class CoverageStore {
  /** filePath → lineNumber → Set<testId> */
  private reverseMap: CoverageMap = {};

  /** testId → Set<"filePath:lineNumber"> */
  private forwardMap: PerTestCoverage = {};

  /** filePath → FileCoverage (aggregate, not per-test) */
  private fileCoverageCache: Map<string, FileCoverage> = new Map();

  /**
   * Parse a Cobertura XML coverage file (generated by Coverlet).
   * Returns aggregated per-file coverage data.
   */
  parseCoberturaXml(xmlPath: string): FileCoverage[] {
    try {
      // Guard against oversized XML files (DoS prevention)
      const stat = fs.statSync(xmlPath);
      if (stat.size > MAX_XML_SIZE) {
        logError(`Cobertura XML too large (${Math.round(stat.size / 1024 / 1024)}MB), skipping`);
        return [];
      }

      const xml = fs.readFileSync(xmlPath, 'utf-8');
      const parser = new XMLParser({
        ignoreAttributes: false,
        attributeNamePrefix: '@_',
        isArray: (name) => ['package', 'class', 'line', 'method'].includes(name),
      });
      const parsed = parser.parse(xml);
      const coverage = parsed.coverage;
      if (!coverage) {
        logError('Invalid Cobertura XML: no <coverage> root element');
        return [];
      }

      const results: FileCoverage[] = [];
      const packages = this.ensureArray(coverage.packages?.package ?? []);

      for (const pkg of packages) {
        const classes = this.ensureArray(pkg.classes?.class ?? []);
        for (const cls of classes) {
          const fileName = cls['@_filename'];
          if (!fileName) { continue; }

          // Resolve to absolute path
          const sources = this.ensureArray(coverage.sources?.source ?? []);
          let filePath = fileName;
          let resolved = false;
          for (const src of sources) {
            const candidate = path.resolve(String(src), fileName);
            if (fs.existsSync(candidate)) {
              filePath = candidate;
              resolved = true;
              break;
            }
          }
          if (!resolved) {
            log(`Coverage: could not resolve path "${fileName}" (sources: ${sources.join(', ')})`);
          }

          // Validate path stays within workspace (path traversal prevention)
          const workspaceRoots = vscode.workspace.workspaceFolders?.map(f => f.uri.fsPath) ?? [];
          if (resolved && workspaceRoots.length > 0) {
            const absPath = path.resolve(filePath);
            const inWorkspace = workspaceRoots.some(root => absPath.startsWith(root));
            if (!inWorkspace) {
              logVerbose(`Coverage: skipping path outside workspace: ${absPath}`);
              continue;
            }
          }

          const lines: LineCoverage[] = [];
          const lineElements = this.ensureArray(cls.lines?.line ?? []);
          for (const line of lineElements) {
            const lineNum = parseInt(line['@_number'], 10);
            const hits = parseInt(line['@_hits'], 10);
            if (!isNaN(lineNum)) {
              lines.push({
                lineNumber: lineNum,
                hits,
                branchCoverage: line['@_condition-coverage']
                  ? this.parseBranchCoverage(line['@_condition-coverage'])
                  : undefined,
              });
            }
          }

          const lineRate = parseFloat(cls['@_line-rate'] ?? '0');
          const branchRate = parseFloat(cls['@_branch-rate'] ?? '0');

          const normalizedFilePath = this.normalizePath(filePath);
          const fc: FileCoverage = { filePath: normalizedFilePath, lines, lineRate, branchRate };
          results.push(fc);
          this.fileCoverageCache.set(normalizedFilePath, fc);
        }
      }

      log(`Parsed Cobertura coverage: ${results.length} files`);
      return results;
    } catch (err) {
      logError('Failed to parse Cobertura XML', err);
      return [];
    }
  }

  /**
   * Parse per-test Coverlet JSON coverage output.
   * Coverlet with `--collect:"XPlat Code Coverage"` and DataCollector options can produce
   * JSON with per-test detail. This is the key to impact analysis.
   *
   * The format is: { "Modules": { "AssemblyName.dll": { "Namespace.Class": { "Method": { "Lines": {...}, "Branches": {...} } } } }
   *
   * For per-test granularity, we rely on running tests individually or in small batches
   * and associating each coverage run with the test(s) that produced it.
   */
  ingestCoverageForTests(testIds: string[], coverageFiles: FileCoverage[]): void {
    for (const fc of coverageFiles) {
      const normalizedPath = this.normalizePath(fc.filePath);

      if (!this.reverseMap[normalizedPath]) {
        this.reverseMap[normalizedPath] = {};
      }

      for (const line of fc.lines) {
        if (line.hits > 0) {
          if (!this.reverseMap[normalizedPath][line.lineNumber]) {
            this.reverseMap[normalizedPath][line.lineNumber] = new Set();
          }

          for (const testId of testIds) {
            this.reverseMap[normalizedPath][line.lineNumber].add(testId);

            // Forward map
            if (!this.forwardMap[testId]) {
              this.forwardMap[testId] = new Set();
            }
            this.forwardMap[testId].add(`${normalizedPath}:${line.lineNumber}`);
          }
        }
      }
    }

    logVerbose(`Ingested coverage for ${testIds.length} tests across ${coverageFiles.length} files`);
  }

  /**
   * Given a file path and set of changed lines, return the test IDs that cover those lines.
   * This is the core of impact analysis.
   */
  getAffectedTests(filePath: string, changedLines: number[]): string[] {
    const normalizedPath = this.normalizePath(filePath);
    const fileMap = this.reverseMap[normalizedPath];
    if (!fileMap) { return []; }

    const affectedTests = new Set<string>();
    for (const line of changedLines) {
      const tests = fileMap[line];
      if (tests) {
        for (const testId of tests) {
          affectedTests.add(testId);
        }
      }
    }

    return Array.from(affectedTests);
  }

  /**
   * Get all test IDs that have any coverage on the given file.
   */
  getTestsForFile(filePath: string): string[] {
    const normalizedPath = this.normalizePath(filePath);
    const fileMap = this.reverseMap[normalizedPath];
    if (!fileMap) { return []; }

    const tests = new Set<string>();
    for (const lineTests of Object.values(fileMap)) {
      for (const testId of lineTests) {
        tests.add(testId);
      }
    }
    return Array.from(tests);
  }

  /**
   * Get coverage data for a specific file.
   */
  getFileCoverage(filePath: string): FileCoverage | undefined {
    return this.fileCoverageCache.get(this.normalizePath(filePath));
  }

  /**
   * Get the set of lines covered by any test in a file.
   */
  getCoveredLines(filePath: string): Set<number> {
    const normalizedPath = this.normalizePath(filePath);
    const fileMap = this.reverseMap[normalizedPath];
    if (!fileMap) { return new Set(); }
    return new Set(Object.keys(fileMap).map(Number));
  }

  /**
   * Get the test IDs covering a specific line.
   */
  getTestsForLine(filePath: string, lineNumber: number): string[] {
    const normalizedPath = this.normalizePath(filePath);
    const tests = this.reverseMap[normalizedPath]?.[lineNumber];
    return tests ? Array.from(tests) : [];
  }

  /**
   * Clear coverage data for specific tests (before re-running them).
   */
  clearTestCoverage(testIds: string[]): void {
    for (const testId of testIds) {
      const locations = this.forwardMap[testId];
      if (locations) {
        for (const loc of locations) {
          const [filePath, lineStr] = loc.split(':');
          const line = parseInt(lineStr, 10);
          const tests = this.reverseMap[filePath]?.[line];
          if (tests) {
            tests.delete(testId);
            if (tests.size === 0) {
              delete this.reverseMap[filePath][line];
            }
          }
        }
        delete this.forwardMap[testId];
      }
    }
  }

  /**
   * Reset all coverage data.
   */
  reset(): void {
    this.reverseMap = {};
    this.forwardMap = {};
    this.fileCoverageCache.clear();
    log('Coverage map reset');
  }

  /**
   * Get aggregate metrics.
   */
  getMetrics(): { totalFiles: number; totalCoveredLines: number; totalInstrumentedLines: number; totalTests: number } {
    let totalCoveredLines = 0;
    let totalInstrumentedLines = 0;
    for (const fc of this.fileCoverageCache.values()) {
      totalInstrumentedLines += fc.lines.length;
      for (const line of fc.lines) {
        if (line.hits > 0) { totalCoveredLines++; }
      }
    }
    return {
      totalFiles: this.fileCoverageCache.size,
      totalCoveredLines,
      totalInstrumentedLines,
      totalTests: Object.keys(this.forwardMap).length,
    };
  }

  // ── Helpers ──────────────────────────────────────────────────────────

  private normalizePath(p: string): string {
    return path.normalize(p).replace(/\\/g, '/');
  }

  private ensureArray<T>(value: T | T[]): T[] {
    return Array.isArray(value) ? value : value ? [value] : [];
  }

  private parseBranchCoverage(condStr: string): number {
    // e.g. "100% (2/2)" → 1.0 or "50% (1/2)" → 0.5
    const match = condStr.match(/(\d+)%/);
    return match ? parseInt(match[1], 10) / 100 : 0;
  }
}
